services:

  frontend-service:
    build:
      context: ./frontend_service
      dockerfile: Dockerfile
      target: development
    container_name: go-micro-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
    networks:
      - microservices
  api-gateway:
    build:
      context: .
      dockerfile: ./api_gateway/Dockerfile
    container_name: go-micro-api-gateway
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./api_gateway/.env
    depends_on:
      - user-service
      - auth-service
      - product-service
    networks:
      - microservices

  user-service:
    build:
      context: .
      dockerfile: ./user_service/Dockerfile
    container_name: go-micro-user-service
    restart: always
    ports:
      - "50051:50051"
    volumes:
      - ./user_service:/app
    env_file:
      - ./user_service/.env
    depends_on:
      - mongo
    networks:
      - microservices

  auth-service:
    build:
      context: .
      dockerfile: ./auth_service/Dockerfile
    container_name: go-micro-auth-service
    restart: always
    ports:
      - "50052:50052"
    env_file:
      - ./auth_service/.env
    depends_on:
      - mongo
      - redis
    networks:
      - microservices

  product-service:
    build:
      context: .
      dockerfile: ./product_service/Dockerfile
    container_name: go-micro-product-service
    restart: always
    ports:
      - "50053:50053"
    env_file:
      - ./product_service/.env
    depends_on:
      - mongo
      - redis
    networks:
      - microservices

  mongo:
    image: mongo:6
    container_name: go-micro-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - microservices

  redis:
    image: redis:7
    container_name: go-micro-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - microservices

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
    - microservices

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Jaeger collector
      - "14250:14250"  # gRPC
      - "6831:6831/udp"  # Jaeger agent
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - microservices

volumes:
  mongo-data:

networks:
  microservices:
    driver: bridge