replicaCount: 1

image:
  repository: 114851843413.dkr.ecr.eu-central-1.amazonaws.com/go-microservice/user-service
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: ecr-secret

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 50051

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  exec:
    command:
      - /bin/grpc-health-probe
      - -addr=:50051
  initialDelaySeconds: 10
  periodSeconds: 10

readinessProbe:
  exec:
    command:
      - /bin/grpc-health-probe
      - -addr=:50051
  initialDelaySeconds: 10
  periodSeconds: 10

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

secrets:
  mongoUri: "mongodb://localhost:27017"
  redisAddr: "go-microservices-elasticache-mlep6v.serverless.euc1.cache.amazonaws.com:6379"
  redisTls: "false"
  jwtSecret: "your-secret-jwt-key-change-me-in-production"
  rabbitmqUri: "amqp://guest:guest@rabbitmq:5672/"

env:
  port: "50051"
  mongoDb: "gomicrodb"
  jaegerEndpoint: "jaeger-all-in-one.tracing.svc.cluster.local:4317"
