global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:2112']

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:2112']

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:2112']
