apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: go-microservices
  region: eu-central-1
  version: "1.29"

vpc:
  id: "vpc-0d460fd597cbcc31b"
  subnets:
    private:
      eu-central-1a:
        id: "subnet-045331dae73e5d89f"
      eu-central-1b:
        id: "subnet-0283c16696ef5348d"
    public:
      eu-central-1a:
        id: "subnet-0cdd46c881baf61af"
      eu-central-1b:
        id: "subnet-025925243c4b0b3d5"

managedNodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    privateNetworking: true
