apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: go-microservices
  region: eu-central-1
  version: "1.35"

vpc:
  id: "vpc-04f534c012342639b"
  subnets:
    private:
      eu-central-1a:
        id: "subnet-0b39069ec80a76510"
      eu-central-1b:
        id: "subnet-013c47ce9af92ae35"
    public:
      eu-central-1a:
        id: "subnet-03f95515e3f65bd2a"
      eu-central-1b:
        id: "subnet-0fe573c19c254c327"

managedNodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    privateNetworking: true



# private_subnet_ids = [
#   "subnet-07cd9eef3013166e9",
#   "subnet-0c2d8e899e0af4a39",
# ]
# public_subnet_ids = [
#   "subnet-011ec8236a32db47d",
#   "subnet-0594e301296029a2a",
# ]
# redis_endpoint = "go-microservices-elasticache-mlep6v.serverless.euc1.cache.amazonaws.com"
# redis_port = 6379
# redis_sg_id = "sg-07d4d8a55540ab7b4"
# vpc_id = "vpc-024ed9aaf851441f1"