apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: go-microservices
  region: eu-central-1
  version: "1.35"

vpc:
  id: "vpc-01ab3fec806555ef8"
  subnets:
    private:
      eu-central-1a:
        id: "subnet-08da55ba2618bd347"
      eu-central-1b:
        id: "subnet-0dbe4e81249fc3d86"
    public:
      eu-central-1a:
        id: "subnet-0e50d9e5ed948cecc"
      eu-central-1b:
        id: "subnet-045f84af2c648ecd6"

managedNodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    privateNetworking: true



# private_subnet_ids = [
#   "subnet-08da55ba2618bd347",
#   "subnet-0dbe4e81249fc3d86",
# ]
# public_subnet_ids = [
#   "subnet-0e50d9e5ed948cecc",
#   "subnet-045f84af2c648ecd6",
# ]
# redis_endpoint = "go-microservices-elasticache-mlep6v.serverless.euc1.cache.amazonaws.com"
# redis_port = 6379
# redis_sg_id = "sg-07f125b2c692b8c5c"
# vpc_id = "vpc-01ab3fec806555ef8"