apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: go-microservices
  region: eu-central-1
  version: "1.35"

vpc:
  id: "vpc-0d10c2658baffeac5"
  subnets:
    private:
      eu-central-1a:
        id: "subnet-069c8a829bdd829ee"
      eu-central-1b:
        id: "subnet-0c9b19a081ec7ea54"
    public:
      eu-central-1a:
        id: "subnet-05e83956af121809d"
      eu-central-1b:
        id: "subnet-042f56325de75abe4"

managedNodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    privateNetworking: true



# Outputs:

# private_subnet_ids = [
#   "subnet-069c8a829bdd829ee",
#   "subnet-0c9b19a081ec7ea54",
# ]
# public_subnet_ids = [
#   "subnet-05e83956af121809d",
#   "subnet-042f56325de75abe4",
# ]
# redis_endpoint = "go-microservices-elasticache-mlep6v.serverless.euc1.cache.amazonaws.com"
# redis_port = 6379
# redis_sg_id = "sg-0a0c228b1ab67a041"
# vpc_id = "vpc-0d10c2658baffeac5"