alertmanager:
  enabled: true

serverFiles:
  alerting_rules.yml:
    groups:
      - name: user-service-alerts
        rules:
          - alert: HighRegisterUserRequestRate
            expr: increase(user_service_requests_total{endpoint="RegisterUser"}[5m]) > 10
            for: 1m
            labels:
              severity: warning
            annotations:
              summary: "High rate of RegisterUser requests detected"
              description: "RegisterUser endpoint received more than 10 requests in the last 5 minutes."
