apiVersion: v1
kind: Secret
metadata:
  name: {{ include "email-service.fullname" . }}-secrets
type: Opaque
stringData:
  RABBITMQ_CONNECTION_STRING: {{ .Values.secrets.rabbitmqConnectionString | quote }}
