apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "email-service.fullname" . }}
  namespace: monitoring
  labels:
    release: monitoring
    {{- include "email-service.labels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      {{- include "email-service.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
